name: Publish Plugins

on:
  release:
    types: [ released ]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew
      - name: Grant Permission to scripts
        run: chmod +x ./scripts/publish_plugins_remote.sh

      - name: Release build
        run: ./gradlew build

      - name: Publish to MavenCentral
        run: ./scripts/publish_plugins_remote.sh
        env:
          REMOTE_REPO_PUBLIC_URL: ${{ secrets.ARTIFACTORY_PUBLIC_URL }}
          REMOTE_REPO_PUBLIC_USER: ${{ secrets.ARTIFACTORY_PUBLIC_USER }}
          REMOTE_REPO_PUBLIC_PASSWORD: ${{ secrets.ARTIFACTORY_PUBLIC_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
